---
language: python
sudo: false
cache: pip
matrix:
  allow_failures:
    - python: nightly
  exclude:
    - python: "3.3"
      env: DJANGO="Django>=1.9.0,<1.10.0"
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
env:
  - DJANGO="Django>=1.8.0,<1.9.0"
  - DJANGO="Django>=1.9.0,<1.10.0"
before_install:
  - pip install -q codecov
install:
  - pip install -q $DJANGO
  - python setup.py -q install
script:
  - coverage run setup.py -v test
after_success:
  - codecov
